### ISSUE TITLE
Webstore App or Source fail to websocket connect 

### ISSUE THREAD

**Issue by ergodaveh** [recisio/karafun-touch#1]
I have tried this Source code and the today's version from the Google Store.

The App - Chrome Extension from the Store and this Source code both have difficuty with the WebSocket..  tcpclient.js:12 WebSocket connection to 'ws://localhost:57570/' failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by cybadr** [comment]
HI, I think the reason is on your configuration.
Please follow this github thread on same issue.
https://github.com/socketio/socket.io/issues/1942

**Comment by tbaranes** [comment]
I'm closing this now, @ergodaveh if you still have a question, feel free to reopen it.
